language: python
jobs:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
install: source .travis_install.sh
env:
  - MPLBACKEND=Agg
script:
  - pytest
  - python setup.py check --restructuredtext --strict
  - rst2html.py --halt=2 README.rst >/dev/null
